[INFO 2023-05-11 15:41:14,385]-> Logs will be saved to /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-11--15-41-14/log.txt
[INFO 2023-05-11 15:41:14,385]-> Files in training will be saved in /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-11--15-41-14
[INFO 2023-05-11 15:41:14,385]-> Random seed is 1683787274
[INFO 2023-05-11 15:41:14,386]-> A new study created in memory with name: no-name-12125028-f00f-4254-a285-e12064134c6d
[WARNING 2023-05-11 15:41:22,348]-> Trial 0 failed with parameters: {"k_['ECG']": 44, "k_['EEG']": 72, "k_['EMO']": 50, "k_['GSR']": 24, "k_['ECG', 'EEG']": 80, "k_['ECG', 'EMO']": 15, "k_['ECG', 'GSR']": 13, "k_['EEG', 'EMO']": 99, "k_['EEG', 'GSR']": 7, "k_['EMO', 'GSR']": 24, "k_['ECG', 'EEG', 'EMO']": 51, "k_['ECG', 'EEG', 'GSR']": 28, "k_['ECG', 'EMO', 'GSR']": 82, "k_['EEG', 'EMO', 'GSR']": 27, "k_['ECG', 'EEG', 'EMO', 'GSR']": 67, 'hidden_dim': 23, 'lr': 0.0030912654611800765, 'weight_decay': 0.005502383320780446} because of the following error: AssertionError('y_true must be 1D torch.LongTensor.').
Traceback (most recent call last):
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 71, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 83, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/base.py", line 103, in experiment
    val_res = self.validate(self.data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 108, in validate
    return super().validate(data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 131, in validate
    res = self.evaluator.validate(labels[val_mask], outputs[val_mask])
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/hypergraphs/hypergraph.py", line 41, in validate
    return super().validate(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 150, in validate
    return super().validate(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/base.py", line 174, in validate
    return self.func_list[self.validate_index](y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 67, in accuracy
    y_true, y_pred = _format_inputs(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 32, in _format_inputs
    assert y_true.dim() == 1, "y_true must be 1D torch.LongTensor."
AssertionError: y_true must be 1D torch.LongTensor.
[WARNING 2023-05-11 15:41:22,349]-> Trial 0 failed with value None.
