[INFO 2023-05-10 18:13:01,835]-> Logs will be saved to /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--18-13-01/log.txt
[INFO 2023-05-10 18:13:01,835]-> Files in training will be saved in /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--18-13-01
[INFO 2023-05-10 18:13:01,836]-> Random seed is 0
[INFO 2023-05-10 18:13:01,837]-> A new study created in memory with name: no-name-8d14fb58-8dc5-4cee-8825-03a5881e261d
[WARNING 2023-05-10 18:13:10,023]-> Trial 0 failed with parameters: {"k_['ECG']": 56, "k_['EEG']": 72, "k_['EMO']": 61, "k_['GSR']": 55, "k_['ECG', 'EEG']": 43, "k_['ECG', 'EMO']": 65, "k_['ECG', 'GSR']": 45, "k_['EEG', 'EMO']": 90, "k_['EEG', 'GSR']": 97, "k_['EMO', 'GSR']": 39, "k_['ECG', 'EEG', 'EMO']": 80, "k_['ECG', 'EEG', 'GSR']": 54, "k_['ECG', 'EMO', 'GSR']": 58, "k_['EEG', 'EMO', 'GSR']": 93, "k_['ECG', 'EEG', 'EMO', 'GSR']": 9, 'hidden_dim': 3, 'lr': 0.00030016213465922467, 'weight_decay': 0.008342936470924586} because of the following error: ValueError('Using a target size (torch.Size([914])) that is different to the input size (torch.Size([914, 2])) is deprecated. Please ensure they have the same size.').
Traceback (most recent call last):
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 71, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 83, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/base.py", line 102, in experiment
    self.train(self.data, model, optimizer, criterion)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 98, in train
    return super().train(data, model, optimizer, criterion)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 115, in train
    loss = criterion(outputs[train_mask], labels[train_mask],)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 619, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 3089, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([914])) that is different to the input size (torch.Size([914, 2])) is deprecated. Please ensure they have the same size.
[WARNING 2023-05-10 18:13:10,024]-> Trial 0 failed with value None.
